#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'hangups==0.3.5','console_scripts','hangups'
__requires__ = 'hangups==0.3.5'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('hangups==0.3.5', 'console_scripts', 'hangups')()
    )
