#!/bin/bash
rofi -color-window "#221b1b, #221b1b, #221b1b" \
	-color-normal "#221b1b, white, #221b1b, #6a4d28, white" \
	-color-active "#221b1b, #6a4d28, #221b1b, #768565, white" \
	-tokenize \
	-hide-scrollbar \
	-lines 10 \
	-width 600 \
	-font "Droid sans mono 8" \
	-show $1
