#!/bin/bash
rofi -color-window "#061f28, #061f28, #061f28" \
	-color-normal "#061f28, white, #061f28, #57737b, white" \
	-color-active "#061f28, #57737b, #061f28, #555D5E, white" \
	-tokenize \
	-hide-scrollbar \
	-lines 10 \
	-width 600 \
	-font "Droid sans mono 8" \
	-show $1
