#!/bin/bash


function mount_local {
	diskd="$( lsblk | grep -Eo "(sda2|sdb2)" )"
	if [ -n "$diskd" ]; then
		diskd="$( echo $diskd | grep -Eo "(sda|sdb)" )"
		sudo mount /dev/"$diskd"1 /media/Local
	else
		echo "No disk to mount, checking with lsblk"
		lsblk
	fi
}

mount_local
