#!/bin/bash

backupdir="/home/reggie/Documents/github/dotfiles"

function up_openbox {
	echo "OPENBOX::BACKUP"
 	cp -r ~/.config/openbox/* $backupdir/openbox/
	echo "XRES::BACKUP"
	cp ~/.Xresources $backupdir/Xresources
	echo "TMUX::BACKUP"
	cp ~/.tmux.conf $backupdir/tmux/.tmux.conf
	cp ~/.tmuxline $backupdir/tmux/.tmuxline
}

function up_vim {
	echo "VIM::BACKUP"
	cp -r ~/.vim/* $backupdir/vim/
	cd $backupdir/vim/bundle/
	rm -rf ./*/.git*
	cd ~
}

function up_mpd {
	echo "MPDNCMPCPP::BACKUP"
	cp -r ~/.mpd/* $backupdir/mpd/
	cp -r ~/.ncmpcpp/* $backupdir/ncmpcpp/
}

function up_zsh {
	echo "ZSH::BACKUP"
	cp ~/.zshrc $backupdir/zsh/
}

function up_tint2 {
	echo "TINT2::BACKUP"
	cp ~/.config/tint2/tint2rc.base $backupdir/tint2/tint2rc
}

function up_scripts {
	echo "SCRIPTS::BACKUP"
	cp /usr/local/bin/* $backupdir/scripts/
	echo "please clean up scripts directory"
}

up_openbox
up_vim
up_zsh
up_tint2
up_mpd
up_scripts
